[2019-01-21 21:03:08,068 - INFO - koios.spark_session]: Initializing pyspark session
[2019-01-21 21:03:09,588 - INFO - koios.spark_session]: Config: spark.driver.memory, value: 3G
[2019-01-21 21:03:09,588 - INFO - koios.spark_session]: Config: spark.master, value: local
[2019-01-21 21:03:09,588 - INFO - koios.spark_session]: Config: spark.rdd.compress, value: True
[2019-01-21 21:03:09,588 - INFO - koios.spark_session]: Config: spark.serializer.objectStreamReset, value: 100
[2019-01-21 21:03:09,588 - INFO - koios.spark_session]: Config: spark.driver.host, value: 192.168.1.33
[2019-01-21 21:03:09,588 - INFO - koios.spark_session]: Config: spark.executor.id, value: driver
[2019-01-21 21:03:09,588 - INFO - koios.spark_session]: Config: spark.app.name, value: forest.py
[2019-01-21 21:03:09,589 - INFO - koios.spark_session]: Config: spark.submit.deployMode, value: client
[2019-01-21 21:03:09,589 - INFO - koios.spark_session]: Config: spark.driver.port, value: 35895
[2019-01-21 21:03:09,589 - INFO - koios.spark_session]: Config: spark.app.id, value: local-1548100988957
[2019-01-21 21:03:09,620 - INFO - koios.io.io]: Reading tsv: data/single_cell_imaging_data.tsv
[2019-01-21 21:03:14,531 - INFO - koios.spark.features]: Casting columns to double.
[2019-01-21 21:03:15,852 - INFO - koios.spark.features]: Assembling column to feature vector
[2019-01-21 21:03:16,053 - INFO - koios.spark.features]: Dropping redundant columns
[2019-01-21 21:03:16,077 - INFO - __main__]: Fitting forest with family='binomial'
[2019-01-21 21:03:19,714 - INFO - koios.regression]: Serialized 1x Replicated
[2019-01-21 21:03:29,790 - ERROR - __main__]: Some error: 'Field "prediction" does not exist.\nAvailable fields: well, gene, sirna, image_idx, object_idx, is_infected, features'
[2019-01-21 21:03:29,791 - INFO - koios.spark_session]: Stopping Spark context
[2019-01-21 21:08:10,992 - INFO - koios.spark_session]: Initializing pyspark session
[2019-01-21 21:08:12,573 - INFO - koios.spark_session]: Config: spark.driver.memory, value: 3G
[2019-01-21 21:08:12,573 - INFO - koios.spark_session]: Config: spark.master, value: local
[2019-01-21 21:08:12,574 - INFO - koios.spark_session]: Config: spark.driver.port, value: 36503
[2019-01-21 21:08:12,574 - INFO - koios.spark_session]: Config: spark.rdd.compress, value: True
[2019-01-21 21:08:12,574 - INFO - koios.spark_session]: Config: spark.serializer.objectStreamReset, value: 100
[2019-01-21 21:08:12,574 - INFO - koios.spark_session]: Config: spark.driver.host, value: 192.168.1.33
[2019-01-21 21:08:12,574 - INFO - koios.spark_session]: Config: spark.executor.id, value: driver
[2019-01-21 21:08:12,574 - INFO - koios.spark_session]: Config: spark.app.name, value: forest.py
[2019-01-21 21:08:12,574 - INFO - koios.spark_session]: Config: spark.submit.deployMode, value: client
[2019-01-21 21:08:12,574 - INFO - koios.spark_session]: Config: spark.app.id, value: local-1548101291823
[2019-01-21 21:08:12,622 - INFO - koios.io.io]: Reading tsv: data/single_cell_imaging_data.tsv
[2019-01-21 21:08:17,302 - INFO - koios.spark.features]: Casting columns to double.
[2019-01-21 21:08:18,573 - INFO - koios.spark.features]: Assembling column to feature vector
[2019-01-21 21:08:18,895 - INFO - koios.spark.features]: Dropping redundant columns
[2019-01-21 21:08:18,936 - INFO - __main__]: Fitting forest with family='binomial'
[2019-01-21 21:08:22,818 - INFO - koios.regression]: Serialized 1x Replicated
[2019-01-21 21:08:33,186 - ERROR - __main__]: Some error: 'Field "prediction" does not exist.\nAvailable fields: well, gene, sirna, image_idx, object_idx, is_infected, features'
[2019-01-21 21:08:33,186 - INFO - koios.spark_session]: Stopping Spark context
[2019-01-21 21:11:37,044 - INFO - koios.spark_session]: Initializing pyspark session
[2019-01-21 21:11:38,490 - INFO - koios.spark_session]: Config: spark.driver.memory, value: 3G
[2019-01-21 21:11:38,490 - INFO - koios.spark_session]: Config: spark.master, value: local
[2019-01-21 21:11:38,490 - INFO - koios.spark_session]: Config: spark.driver.port, value: 38615
[2019-01-21 21:11:38,490 - INFO - koios.spark_session]: Config: spark.rdd.compress, value: True
[2019-01-21 21:11:38,490 - INFO - koios.spark_session]: Config: spark.serializer.objectStreamReset, value: 100
[2019-01-21 21:11:38,490 - INFO - koios.spark_session]: Config: spark.driver.host, value: 192.168.1.33
[2019-01-21 21:11:38,490 - INFO - koios.spark_session]: Config: spark.executor.id, value: driver
[2019-01-21 21:11:38,490 - INFO - koios.spark_session]: Config: spark.app.name, value: forest.py
[2019-01-21 21:11:38,491 - INFO - koios.spark_session]: Config: spark.submit.deployMode, value: client
[2019-01-21 21:11:38,491 - INFO - koios.spark_session]: Config: spark.app.id, value: local-1548101497908
[2019-01-21 21:11:38,510 - INFO - koios.io.io]: Reading tsv: data/single_cell_imaging_data.tsv
[2019-01-21 21:11:43,207 - INFO - koios.spark.features]: Casting columns to double.
[2019-01-21 21:11:44,434 - INFO - koios.spark.features]: Assembling column to feature vector
[2019-01-21 21:11:44,643 - INFO - koios.spark.features]: Dropping redundant columns
[2019-01-21 21:11:44,693 - INFO - __main__]: sadasdasasdasd
[2019-01-21 21:11:44,693 - INFO - __main__]: Fitting forest with family='binomial'
[2019-01-21 21:11:48,399 - INFO - koios.regression]: Serialized 1x Replicated
[2019-01-21 21:11:58,221 - ERROR - __main__]: Some error: 'Field "prediction" does not exist.\nAvailable fields: well, gene, sirna, image_idx, object_idx, is_infected, features'
[2019-01-21 21:11:58,221 - INFO - koios.spark_session]: Stopping Spark context
[2019-01-21 21:14:46,795 - INFO - koios.spark_session]: Initializing pyspark session
[2019-01-21 21:14:48,711 - INFO - koios.spark_session]: Config: spark.driver.memory, value: 3G
[2019-01-21 21:14:48,711 - INFO - koios.spark_session]: Config: spark.master, value: local
[2019-01-21 21:14:48,711 - INFO - koios.spark_session]: Config: spark.driver.port, value: 45295
[2019-01-21 21:14:48,711 - INFO - koios.spark_session]: Config: spark.rdd.compress, value: True
[2019-01-21 21:14:48,711 - INFO - koios.spark_session]: Config: spark.app.id, value: local-1548101688033
[2019-01-21 21:14:48,711 - INFO - koios.spark_session]: Config: spark.serializer.objectStreamReset, value: 100
[2019-01-21 21:14:48,712 - INFO - koios.spark_session]: Config: spark.driver.host, value: 192.168.1.33
[2019-01-21 21:14:48,712 - INFO - koios.spark_session]: Config: spark.executor.id, value: driver
[2019-01-21 21:14:48,712 - INFO - koios.spark_session]: Config: spark.app.name, value: forest.py
[2019-01-21 21:14:48,712 - INFO - koios.spark_session]: Config: spark.submit.deployMode, value: client
[2019-01-21 21:14:48,730 - INFO - koios.io.io]: Reading tsv: data/single_cell_imaging_data.tsv
[2019-01-21 21:14:53,376 - INFO - koios.spark.features]: Casting columns to double.
[2019-01-21 21:14:54,776 - INFO - koios.spark.features]: Assembling column to feature vector
[2019-01-21 21:14:55,031 - INFO - koios.spark.features]: Dropping redundant columns
[2019-01-21 21:14:55,092 - INFO - __main__]: sadasdasasdasd
[2019-01-21 21:14:55,092 - INFO - __main__]: Fitting forest with family='binomial'
[2019-01-21 21:14:59,161 - INFO - koios.regression]: Serialized 1x Replicated
[2019-01-21 21:15:07,721 - ERROR - __main__]: Some error: 'Field "prediction" does not exist.\nAvailable fields: well, gene, sirna, image_idx, object_idx, is_infected, features'
[2019-01-21 21:15:07,721 - INFO - koios.spark_session]: Stopping Spark context
[2019-01-21 21:15:42,283 - INFO - koios.spark_session]: Initializing pyspark session
[2019-01-21 21:15:43,657 - INFO - koios.spark_session]: Config: spark.driver.memory, value: 3G
[2019-01-21 21:15:43,657 - INFO - koios.spark_session]: Config: spark.master, value: local
[2019-01-21 21:15:43,657 - INFO - koios.spark_session]: Config: spark.driver.port, value: 42231
[2019-01-21 21:15:43,657 - INFO - koios.spark_session]: Config: spark.rdd.compress, value: True
[2019-01-21 21:15:43,657 - INFO - koios.spark_session]: Config: spark.serializer.objectStreamReset, value: 100
[2019-01-21 21:15:43,657 - INFO - koios.spark_session]: Config: spark.driver.host, value: 192.168.1.33
[2019-01-21 21:15:43,657 - INFO - koios.spark_session]: Config: spark.executor.id, value: driver
[2019-01-21 21:15:43,657 - INFO - koios.spark_session]: Config: spark.app.name, value: forest.py
[2019-01-21 21:15:43,657 - INFO - koios.spark_session]: Config: spark.submit.deployMode, value: client
[2019-01-21 21:15:43,658 - INFO - koios.spark_session]: Config: spark.app.id, value: local-1548101743010
[2019-01-21 21:15:43,680 - INFO - koios.io.io]: Reading tsv: data/single_cell_imaging_data.tsv
[2019-01-21 21:15:48,669 - INFO - koios.spark.features]: Casting columns to double.
[2019-01-21 21:15:49,978 - INFO - koios.spark.features]: Assembling column to feature vector
[2019-01-21 21:15:50,185 - INFO - koios.spark.features]: Dropping redundant columns
[2019-01-21 21:15:50,234 - INFO - __main__]: sadasdasasdasd
[2019-01-21 21:15:50,234 - INFO - __main__]: Fitting forest with family='binomial'
[2019-01-21 21:15:53,981 - INFO - koios.regression]: Serialized 1x Replicated
[2019-01-21 21:15:54,010 - INFO - __main__]: is_infected
[2019-01-21 21:16:04,242 - ERROR - __main__]: Some error: 'Field "prediction" does not exist.\nAvailable fields: well, gene, sirna, image_idx, object_idx, is_infected, features'
[2019-01-21 21:16:04,242 - INFO - koios.spark_session]: Stopping Spark context
[2019-01-21 21:18:35,219 - INFO - koios.spark_session]: Initializing pyspark session
[2019-01-21 21:18:36,727 - INFO - koios.spark_session]: Config: spark.driver.memory, value: 3G
[2019-01-21 21:18:36,728 - INFO - koios.spark_session]: Config: spark.master, value: local
[2019-01-21 21:18:36,728 - INFO - koios.spark_session]: Config: spark.rdd.compress, value: True
[2019-01-21 21:18:36,728 - INFO - koios.spark_session]: Config: spark.serializer.objectStreamReset, value: 100
[2019-01-21 21:18:36,728 - INFO - koios.spark_session]: Config: spark.app.id, value: local-1548101916107
[2019-01-21 21:18:36,728 - INFO - koios.spark_session]: Config: spark.driver.host, value: 192.168.1.33
[2019-01-21 21:18:36,728 - INFO - koios.spark_session]: Config: spark.executor.id, value: driver
[2019-01-21 21:18:36,728 - INFO - koios.spark_session]: Config: spark.app.name, value: forest.py
[2019-01-21 21:18:36,728 - INFO - koios.spark_session]: Config: spark.submit.deployMode, value: client
[2019-01-21 21:18:36,728 - INFO - koios.spark_session]: Config: spark.driver.port, value: 41621
[2019-01-21 21:18:36,746 - INFO - koios.io.io]: Reading tsv: data/single_cell_imaging_data.tsv
[2019-01-21 21:18:41,237 - INFO - koios.spark.features]: Casting columns to double.
[2019-01-21 21:18:42,421 - INFO - koios.spark.features]: Assembling column to feature vector
[2019-01-21 21:18:42,694 - INFO - koios.spark.features]: Dropping redundant columns
[2019-01-21 21:18:42,710 - INFO - __main__]: sadasdasasdasd
[2019-01-21 21:18:42,710 - INFO - __main__]: Fitting forest with family='binomial'
[2019-01-21 21:18:46,228 - INFO - koios.regression]: Serialized 1x Replicated
[2019-01-21 21:18:46,249 - INFO - __main__]: is_infected
[2019-01-21 21:18:56,536 - ERROR - __main__]: Some error: 'Field "prediction" does not exist.\nAvailable fields: well, gene, sirna, image_idx, object_idx, is_infected, features'
[2019-01-21 21:18:56,536 - INFO - koios.spark_session]: Stopping Spark context
[2019-01-21 21:20:46,081 - INFO - koios.spark_session]: Initializing pyspark session
[2019-01-21 21:20:47,548 - INFO - koios.spark_session]: Config: spark.driver.memory, value: 3G
[2019-01-21 21:20:47,548 - INFO - koios.spark_session]: Config: spark.master, value: local
[2019-01-21 21:20:47,548 - INFO - koios.spark_session]: Config: spark.driver.port, value: 40769
[2019-01-21 21:20:47,548 - INFO - koios.spark_session]: Config: spark.rdd.compress, value: True
[2019-01-21 21:20:47,548 - INFO - koios.spark_session]: Config: spark.serializer.objectStreamReset, value: 100
[2019-01-21 21:20:47,548 - INFO - koios.spark_session]: Config: spark.driver.host, value: 192.168.1.33
[2019-01-21 21:20:47,548 - INFO - koios.spark_session]: Config: spark.executor.id, value: driver
[2019-01-21 21:20:47,548 - INFO - koios.spark_session]: Config: spark.app.name, value: forest.py
[2019-01-21 21:20:47,548 - INFO - koios.spark_session]: Config: spark.submit.deployMode, value: client
[2019-01-21 21:20:47,549 - INFO - koios.spark_session]: Config: spark.app.id, value: local-1548102046909
[2019-01-21 21:20:47,573 - INFO - koios.io.io]: Reading tsv: data/single_cell_imaging_data.tsv
[2019-01-21 21:20:52,009 - INFO - koios.spark.features]: Casting columns to double.
[2019-01-21 21:20:53,264 - INFO - koios.spark.features]: Assembling column to feature vector
[2019-01-21 21:20:53,438 - INFO - koios.spark.features]: Dropping redundant columns
[2019-01-21 21:20:53,488 - INFO - __main__]: sadasdasasdasd
[2019-01-21 21:20:53,488 - INFO - __main__]: Fitting forest with family='binomial'
[2019-01-21 21:20:57,336 - INFO - koios.regression]: Serialized 1x Replicated
[2019-01-21 21:20:57,367 - INFO - __main__]: is_infected
[2019-01-21 21:20:57,368 - ERROR - __main__]: Some error: name 'model' is not defined
[2019-01-21 21:20:57,368 - INFO - koios.spark_session]: Stopping Spark context
[2019-01-21 21:21:39,498 - INFO - koios.spark_session]: Initializing pyspark session
[2019-01-21 21:21:40,900 - INFO - koios.spark_session]: Config: spark.driver.memory, value: 3G
[2019-01-21 21:21:40,900 - INFO - koios.spark_session]: Config: spark.master, value: local
[2019-01-21 21:21:40,900 - INFO - koios.spark_session]: Config: spark.driver.port, value: 37343
[2019-01-21 21:21:40,900 - INFO - koios.spark_session]: Config: spark.rdd.compress, value: True
[2019-01-21 21:21:40,900 - INFO - koios.spark_session]: Config: spark.app.id, value: local-1548102100269
[2019-01-21 21:21:40,900 - INFO - koios.spark_session]: Config: spark.serializer.objectStreamReset, value: 100
[2019-01-21 21:21:40,900 - INFO - koios.spark_session]: Config: spark.driver.host, value: 192.168.1.33
[2019-01-21 21:21:40,900 - INFO - koios.spark_session]: Config: spark.executor.id, value: driver
[2019-01-21 21:21:40,900 - INFO - koios.spark_session]: Config: spark.app.name, value: forest.py
[2019-01-21 21:21:40,900 - INFO - koios.spark_session]: Config: spark.submit.deployMode, value: client
[2019-01-21 21:21:40,920 - INFO - koios.io.io]: Reading tsv: data/single_cell_imaging_data.tsv
[2019-01-21 21:21:45,353 - INFO - koios.spark.features]: Casting columns to double.
[2019-01-21 21:21:46,473 - INFO - koios.spark.features]: Assembling column to feature vector
[2019-01-21 21:21:46,664 - INFO - koios.spark.features]: Dropping redundant columns
[2019-01-21 21:21:46,690 - INFO - __main__]: sadasdasasdasd
[2019-01-21 21:21:46,691 - INFO - __main__]: Fitting forest with family='binomial'
[2019-01-21 21:21:50,291 - INFO - koios.regression]: Serialized 1x Replicated
[2019-01-21 21:21:50,326 - INFO - __main__]: is_infected
[2019-01-21 21:22:00,246 - ERROR - __main__]: Some error: 'Field "prediction" does not exist.\nAvailable fields: well, gene, sirna, image_idx, object_idx, is_infected, features'
[2019-01-21 21:22:00,246 - INFO - koios.spark_session]: Stopping Spark context
[2019-01-21 21:24:30,614 - INFO - koios.spark_session]: Initializing pyspark session
[2019-01-21 21:24:32,030 - INFO - koios.spark_session]: Config: spark.driver.memory, value: 3G
[2019-01-21 21:24:32,030 - INFO - koios.spark_session]: Config: spark.master, value: local
[2019-01-21 21:24:32,030 - INFO - koios.spark_session]: Config: spark.rdd.compress, value: True
[2019-01-21 21:24:32,030 - INFO - koios.spark_session]: Config: spark.app.id, value: local-1548102271425
[2019-01-21 21:24:32,030 - INFO - koios.spark_session]: Config: spark.serializer.objectStreamReset, value: 100
[2019-01-21 21:24:32,030 - INFO - koios.spark_session]: Config: spark.driver.host, value: 192.168.1.33
[2019-01-21 21:24:32,030 - INFO - koios.spark_session]: Config: spark.executor.id, value: driver
[2019-01-21 21:24:32,030 - INFO - koios.spark_session]: Config: spark.app.name, value: forest.py
[2019-01-21 21:24:32,030 - INFO - koios.spark_session]: Config: spark.submit.deployMode, value: client
[2019-01-21 21:24:32,030 - INFO - koios.spark_session]: Config: spark.driver.port, value: 34143
[2019-01-21 21:24:32,042 - INFO - koios.io.io]: Reading tsv: data/single_cell_imaging_data.tsv
[2019-01-21 21:24:36,606 - INFO - koios.spark.features]: Casting columns to double.
[2019-01-21 21:24:37,929 - INFO - koios.spark.features]: Assembling column to feature vector
[2019-01-21 21:24:38,181 - INFO - koios.spark.features]: Dropping redundant columns
[2019-01-21 21:24:38,225 - INFO - __main__]: sadasdasasdasd
[2019-01-21 21:24:38,225 - INFO - __main__]: Fitting forest with family='binomial'
[2019-01-21 21:24:42,137 - INFO - koios.regression]: Serialized 1x Replicated
[2019-01-21 21:24:42,160 - INFO - __main__]: is_infected
[2019-01-21 21:24:42,160 - INFO - koios.regression]: is_infected
[2019-01-21 21:24:52,343 - ERROR - __main__]: Some error: 'Field "prediction" does not exist.\nAvailable fields: well, gene, sirna, image_idx, object_idx, is_infected, features'
[2019-01-21 21:24:52,343 - INFO - koios.spark_session]: Stopping Spark context
[2019-01-21 21:26:20,966 - INFO - koios.spark_session]: Initializing pyspark session
[2019-01-21 21:26:22,458 - INFO - koios.spark_session]: Config: spark.driver.memory, value: 3G
[2019-01-21 21:26:22,458 - INFO - koios.spark_session]: Config: spark.master, value: local
[2019-01-21 21:26:22,458 - INFO - koios.spark_session]: Config: spark.rdd.compress, value: True
[2019-01-21 21:26:22,458 - INFO - koios.spark_session]: Config: spark.driver.port, value: 45493
[2019-01-21 21:26:22,458 - INFO - koios.spark_session]: Config: spark.serializer.objectStreamReset, value: 100
[2019-01-21 21:26:22,458 - INFO - koios.spark_session]: Config: spark.driver.host, value: 192.168.1.33
[2019-01-21 21:26:22,458 - INFO - koios.spark_session]: Config: spark.executor.id, value: driver
[2019-01-21 21:26:22,458 - INFO - koios.spark_session]: Config: spark.app.name, value: forest.py
[2019-01-21 21:26:22,458 - INFO - koios.spark_session]: Config: spark.submit.deployMode, value: client
[2019-01-21 21:26:22,458 - INFO - koios.spark_session]: Config: spark.app.id, value: local-1548102381814
[2019-01-21 21:26:22,487 - INFO - koios.io.io]: Reading tsv: data/single_cell_imaging_data.tsv
[2019-01-21 21:26:26,941 - INFO - koios.spark.features]: Casting columns to double.
[2019-01-21 21:26:28,064 - INFO - koios.spark.features]: Assembling column to feature vector
[2019-01-21 21:26:28,401 - INFO - koios.spark.features]: Dropping redundant columns
[2019-01-21 21:26:28,427 - INFO - __main__]: sadasdasasdasd
[2019-01-21 21:26:28,427 - INFO - __main__]: Fitting forest with family='binomial'
[2019-01-21 21:26:32,110 - INFO - koios.regression]: Serialized 1x Replicated
[2019-01-21 21:26:32,150 - INFO - __main__]: is_infected
[2019-01-21 21:26:32,150 - INFO - koios.regression]: is_infected
[2019-01-21 21:26:41,874 - INFO - __main__]: sadasdasd123123
[2019-01-21 21:26:41,915 - ERROR - __main__]: Some error: 'Field "prediction" does not exist.\nAvailable fields: well, gene, sirna, image_idx, object_idx, is_infected, features'
[2019-01-21 21:26:41,916 - INFO - koios.spark_session]: Stopping Spark context
[2019-01-21 21:29:56,787 - INFO - koios.spark_session]: Initializing pyspark session
[2019-01-21 21:29:58,261 - INFO - koios.spark_session]: Config: spark.driver.memory, value: 3G
[2019-01-21 21:29:58,261 - INFO - koios.spark_session]: Config: spark.master, value: local
[2019-01-21 21:29:58,261 - INFO - koios.spark_session]: Config: spark.driver.port, value: 32799
[2019-01-21 21:29:58,261 - INFO - koios.spark_session]: Config: spark.rdd.compress, value: True
[2019-01-21 21:29:58,261 - INFO - koios.spark_session]: Config: spark.app.id, value: local-1548102597616
[2019-01-21 21:29:58,261 - INFO - koios.spark_session]: Config: spark.serializer.objectStreamReset, value: 100
[2019-01-21 21:29:58,261 - INFO - koios.spark_session]: Config: spark.driver.host, value: 192.168.1.33
[2019-01-21 21:29:58,262 - INFO - koios.spark_session]: Config: spark.executor.id, value: driver
[2019-01-21 21:29:58,262 - INFO - koios.spark_session]: Config: spark.app.name, value: forest.py
[2019-01-21 21:29:58,262 - INFO - koios.spark_session]: Config: spark.submit.deployMode, value: client
[2019-01-21 21:29:58,275 - INFO - koios.io.io]: Reading tsv: data/single_cell_imaging_data.tsv
[2019-01-21 21:30:02,899 - INFO - koios.spark.features]: Casting columns to double.
[2019-01-21 21:30:04,053 - INFO - koios.spark.features]: Assembling column to feature vector
[2019-01-21 21:30:04,318 - INFO - koios.spark.features]: Dropping redundant columns
[2019-01-21 21:30:04,343 - INFO - __main__]: sadasdasasdasd
[2019-01-21 21:30:04,343 - INFO - __main__]: Fitting forest with family='binomial'
[2019-01-21 21:30:07,950 - INFO - __main__]: is_infected
[2019-01-21 21:30:27,343 - INFO - __main__]: sadasdasd
[2019-01-21 21:30:27,343 - INFO - koios.fit.forest_fit]: Writing regression statistics
[2019-01-21 21:30:27,344 - INFO - __main__]: sadasdasd2
[2019-01-21 21:30:27,344 - INFO - koios.io.io]: Reading tsv: data/single_cell_imaging_data.tsv
[2019-01-21 21:30:27,614 - INFO - koios.spark.features]: Casting columns to double.
[2019-01-21 21:30:28,116 - INFO - koios.spark.features]: Assembling column to feature vector
[2019-01-21 21:30:28,237 - INFO - koios.io.io]: Writing parquet: data/forest-transformed
[2019-01-21 21:30:31,383 - INFO - koios.spark.features]: Dropping column 'features'
[2019-01-21 21:30:31,389 - INFO - koios.spark.features]: Dropping column 'rawPrediction'
[2019-01-21 21:30:31,395 - INFO - koios.spark.features]: Splitting vector columns: probability
[2019-01-21 21:30:31,995 - INFO - koios.io.io]: Writing tsv: data/forest-transformed
[2019-01-21 21:30:35,295 - INFO - koios.spark_session]: Stopping Spark context
